import { WordPair, PhrasePair } from './types';

export const ALL_WORDS: WordPair[] = [
  // --- Travel & Transport (50) ---
  { id: 1, english: 'Travel', khmer: 'ធ្វើដំណើរ', category: 'Travel & Transport' },
  { id: 2, english: 'Airplane', khmer: 'យន្តហោះ', category: 'Travel & Transport' },
  { id: 3, english: 'Airport', khmer: 'ព្រលានយន្តហោះ', category: 'Travel & Transport' },
  { id: 4, english: 'Bus', khmer: 'ឡានក្រុង', category: 'Travel & Transport' },
  { id: 5, english: 'Car', khmer: 'ឡាន', category: 'Travel & Transport' },
  { id: 6, english: 'Motorbike', khmer: 'ម៉ូតូ', category: 'Travel & Transport' },
  { id: 7, english: 'Bicycle', khmer: 'កង់', category: 'Travel & Transport' },
  { id: 8, english: 'Tuk-tuk', khmer: 'រ៉ឺម៉ក', category: 'Travel & Transport' },
  { id: 9, english: 'Boat', khmer: 'ទូក', category: 'Travel & Transport' },
  { id: 10, english: 'Ticket', khmer: 'សំបុត្រ', category: 'Travel & Transport' },
  { id: 11, english: 'Passport', khmer: 'លិខិតឆ្លងដែន', category: 'Travel & Transport' },
  { id: 12, english: 'Luggage', khmer: 'អីវ៉ាន់', category: 'Travel & Transport' },
  { id: 13, english: 'Road', khmer: 'ផ្លូវ', category: 'Travel & Transport' },
  { id: 14, english: 'Street', khmer: 'ផ្លូវ', category: 'Travel & Transport' },
  { id: 15, english: 'Gas station', khmer: 'ស្ថានីយ៍ប្រេងឥន្ធនៈ', category: 'Travel & Transport' },
  { id: 16, english: 'Driver', khmer: 'អ្នកបើកបរ', category: 'Travel & Transport' },
  { id: 17, english: 'Journey', khmer: 'ដំណើរ', category: 'Travel & Transport' },
  { id: 18, english: 'Map', khmer: 'ផែនទី', category: 'Travel & Transport' },
  { id: 19, english: 'Direction', khmer: 'ទិសដៅ', category: 'Travel & Transport' },
  { id: 20, english: 'Left', khmer: 'ឆ្វេង', category: 'Travel & Transport' },
  { id: 21, english: 'Right', khmer: 'ស្តាំ', category: 'Travel & Transport' },
  { id: 22, english: 'Straight', khmer: 'ត្រង់', category: 'Travel & Transport' },
  { id: 23, english: 'Stop', khmer: 'ឈប់', category: 'Travel & Transport' },
  { id: 24, english: 'Go', khmer: 'ទៅ', category: 'Travel & Transport' },
  { id: 25, english: 'Here', khmer: 'ទីនេះ', category: 'Travel & Transport' },
  { id: 26, english: 'There', khmer: 'ទីនោះ', category: 'Travel & Transport' },
  { id: 27, english: 'Far', khmer: 'ឆ្ងាយ', category: 'Travel & Transport' },
  { id: 28, english: 'Near', khmer: 'ជិត', category: 'Travel & Transport' },
  { id: 29, english: 'Train', khmer: 'រថភ្លើង', category: 'Travel & Transport' },
  { id: 30, english: 'Station', khmer: 'ស្ថានីយ៍', category: 'Travel & Transport' },
  { id: 31, english: 'Taxi', khmer: 'តាក់ស៊ី', category: 'Travel & Transport' },
  { id: 32, english: 'Bridge', khmer: 'ស្ពាន', category: 'Travel & Transport' },
  { id: 33, english: 'Traffic', khmer: 'ចរាចរណ៍', category: 'Travel & Transport' },
  { id: 34, english: 'Passenger', khmer: 'អ្នកដំណើរ', category: 'Travel & Transport' },
  { id: 35, english: 'To rent', khmer: 'ជួល', category: 'Travel & Transport' },
  { id: 37, english: 'Slowly', khmer: 'យឺតៗ', category: 'Travel & Transport' },
  { id: 38, english: 'Quickly', khmer: 'លឿនៗ', category: 'Travel & Transport' },
  { id: 39, english: 'Arrival', khmer: 'ការមកដល់', category: 'Travel & Transport' },
  { id: 40, english: 'Departure', khmer: 'ការចេញដំណើរ', category: 'Travel & Transport' },
  { id: 41, english: 'Customs', khmer: 'គយ', category: 'Travel & Transport' },
  { id: 42, english: 'Visa', khmer: 'ទិដ្ឋាការ', category: 'Travel & Transport' },
  { id: 43, english: 'One way', khmer: 'ជើងเดียว', category: 'Travel & Transport' },
  { id: 44, english: 'Round trip', khmer: 'ទៅមក', category: 'Travel & Transport' },
  { id: 45, english: 'Intersection', khmer: 'ផ្លូវបំបែក', category: 'Travel & Transport' },
  { id: 46, english: 'Sidewalk', khmer: 'ចិញ្ចើមផ្លូវ', category: 'Travel & Transport' },
  { id: 47, english: 'Vehicle', khmer: 'យានយន្ត', category: 'Travel & Transport' },
  { id: 48, english: 'Fuel', khmer: 'ប្រេងឥន្ធនៈ', category: 'Travel & Transport' },
  { id: 49, english: 'Tourist', khmer: 'អ្នក​ท่องเที่ยว', category: 'Travel & Transport' },
  { id: 50, english: 'Backpack', khmer: 'កាតាប', category: 'Travel & Transport' },

  // --- Accommodation (40) ---
  { id: 51, english: 'Hotel', khmer: 'សណ្ឋាគារ', category: 'Accommodation' },
  { id: 52, english: 'Guesthouse', khmer: 'ផ្ទះសំណាក់', category: 'Accommodation' },
  { id: 53, english: 'Room', khmer: 'បន្ទប់', category: 'Accommodation' },
  { id: 54, english: 'Reservation', khmer: 'ការកក់', category: 'Accommodation' },
  { id: 55, english: 'Key', khmer: 'សោ', category: 'Accommodation' },
  { id: 56, english: 'Bed', khmer: 'គ្រែ', category: 'Accommodation' },
  { id: 57, english: 'Pillow', khmer: 'ខ្នើយ', category: 'Accommodation' },
  { id: 58, english: 'Blanket', khmer: 'ភួយ', category: 'Accommodation' },
  { id: 59, english: 'Bathroom', khmer: 'បន្ទប់ទឹក', category: 'Accommodation' },
  { id: 60, english: 'Toilet', khmer: 'បង្គន់', category: 'Accommodation' },
  { id: 61, english: 'Shower', khmer: 'ផ្កាឈូក', category: 'Accommodation' },
  { id: 62, english: 'Towel', khmer: 'កន្សែង', category: 'Accommodation' },
  { id: 63, english: 'Soap', khmer: 'សាប៊ូ', category: 'Accommodation' },
  { id: 64, english: 'Air conditioning', khmer: 'ម៉ាស៊ីនត្រជាក់', category: 'Accommodation' },
  { id: 65, english: 'Fan', khmer: 'កង្ហារ', category: 'Accommodation' },
  { id: 66, english: 'Window', khmer: 'បង្អួច', category: 'Accommodation' },
  { id: 67, english: 'Door', khmer: 'ទ្វារ', category: 'Accommodation' },
  { id: 68, english: 'Reception', khmer: 'កន្លែងទទួលភ្ញៀវ', category: 'Accommodation' },
  { id: 69, english: 'Check-in', khmer: 'ចុះឈ្មោះចូល', category: 'Accommodation' },
  { id: 70, english: 'Check-out', khmer: 'ចុះឈ្មោះចេញ', category: 'Accommodation' },
  { id: 71, english: 'Price', khmer: 'តម្លៃ', category: 'Accommodation' },
  { id: 72, english: 'Night', khmer: 'យប់', category: 'Accommodation' },
  { id: 73, english: 'Stay', khmer: 'ស្នាក់នៅ', category: 'Accommodation' },
  { id: 74, english: 'Clean', khmer: 'ស្អាត', category: 'Accommodation' },
  { id: 75, english: 'Dirty', khmer: 'កខ្វក់', category: 'Accommodation' },
  { id: 76, english: 'Lobby', khmer: 'ឡប់ប៊ី', category: 'Accommodation' },
  { id: 77, english: 'Elevator', khmer: 'ជណ្តើរយន្ត', category: 'Accommodation' },
  { id: 78, english: 'Stairs', khmer: 'ជណ្តើរ', category: 'Accommodation' },
  { id: 79, english: 'Floor', khmer: 'ជាន់', category: 'Accommodation' },
  { id: 80, english: 'Single room', khmer: 'បន្ទប់គេងមួយ', category: 'Accommodation' },
  { id: 81, english: 'Double room', khmer: 'បន្ទប់គេងពីរ', category: 'Accommodation' },
  { id: 82, english: 'Breakfast', khmer: 'អាហារពេលព្រឹក', category: 'Accommodation' },
  { id: 83, english: 'Wi-Fi', khmer: 'វ៉ាយហ្វាយ', category: 'Accommodation' },
  { id: 84, english: 'Password', khmer: 'ពាក្យសម្ងាត់', category: 'Accommodation' },
  { id: 85, english: 'Hot water', khmer: 'ទឹកក្តៅ', category: 'Accommodation' },
  { id: 86, english: 'Manager', khmer: 'អ្នកគ្រប់គ្រង', category: 'Accommodation' },
  { id: 87, english: 'Available', khmer: 'ទំនេរ', category: 'Accommodation' },
  { id: 88, english: 'Full', khmer: 'ពេញ', category: 'Accommodation' },
  { id: 89, english: 'View', khmer: 'ទេសភាព', category: 'Accommodation' },
  { id: 90, english: 'Balcony', khmer: 'យ៉រ', category: 'Accommodation' },

  // --- Culture & People (40) ---
  { id: 91, english: 'Culture', khmer: 'វប្បធម៌', category: 'Culture & People' },
  { id: 92, english: 'Temple', khmer: 'ប្រាសាទ', category: 'Culture & People' },
  { id: 93, english: 'Pagoda', khmer: 'វត្ត', category: 'Culture & People' },
  { id: 94, english: 'Monk', khmer: 'ព្រះសង្ឃ', category: 'Culture & People' },
  { id: 95, english: 'Buddha', khmer: 'ព្រះពុទ្ធ', category: 'Culture & People' },
  { id: 96, english: 'Statue', khmer: 'រូបសំណាក', category: 'Culture & People' },
  { id: 97, english: 'Dance', khmer: 'របាំ', category: 'Culture & People' },
  { id: 98, english: 'Music', khmer: 'តន្ត្រី', category: 'Culture & People' },
  { id: 99, english: 'Art', khmer: 'សិល្បៈ', category: 'Culture & People' },
  { id: 100, english: 'History', khmer: 'ប្រវត្តិសាស្ត្រ', category: 'Culture & People' },
  { id: 101, english: 'King', khmer: 'ស្តេច', category: 'Culture & People' },
  { id: 102, english: 'Queen', khmer: 'ម្ចាស់ក្សត្រី', category: 'Culture & People' },
  { id: 103, english: 'Family', khmer: 'គ្រួសារ', category: 'Culture & People' },
  { id: 104, english: 'Friend', khmer: 'មិត្តភក្តិ', category: 'Culture & People' },
  { id: 105, english: 'People', khmer: 'ប្រជាជន', category: 'Culture & People' },
  { id: 106, english: 'Man', khmer: 'បុរស', category: 'Culture & People' },
  { id: 107, english: 'Woman', khmer: 'ស្ត្រី', category: 'Culture & People' },
  { id: 108, english: 'Child', khmer: 'កូន', category: 'Culture & People' },
  { id: 109, english: 'Village', khmer: 'ភូមិ', category: 'Culture & People' },
  { id: 110, english: 'City', khmer: 'ទីក្រុង', category: 'Culture & People' },
  { id: 111, english: 'Market', khmer: 'ផ្សារ', category: 'Culture & People' },
  { id: 112, english: 'Festival', khmer: 'ពិធីបុណ្យ', category: 'Culture & People' },
  { id: 113, english: 'Wedding', khmer: 'អាពាហ៍ពិពាហ៍', category: 'Culture & People' },
  { id: 114, english: 'Holiday', khmer: 'ថ្ងៃឈប់សម្រាក', category: 'Culture & People' },
  { id: 115, english: 'Language', khmer: 'ភាសា', category: 'Culture & People' },
  { id: 116, english: 'Tradition', khmer: 'ប្រពៃណី', category: 'Culture & People' },
  { id: 117, english: 'Respect', khmer: 'ការគោរព', category: 'Culture & People' },
  { id: 118, english: 'Hello', khmer: 'សួស្តី', category: 'Culture & People' },
  { id: 120, english: 'Sorry', khmer: 'សុំទោស', category: 'Culture & People' },
  { id: 122, english: 'Beautiful', khmer: 'ស្អាត', category: 'Culture & People' },
  { id: 123, english: 'Happy', khmer: 'សប្បាយ', category: 'Culture & People' },
  { id: 124, english: 'Teacher', khmer: 'គ្រូ', category: 'Culture & People' },
  { id: 125, english: 'Student', khmer: 'សិស្ស', category: 'Culture & People' },
  { id: 126, english: 'Farmer', khmer: 'កសិករ', category: 'Culture & People' },
  { id: 127, english: 'Government', khmer: 'រដ្ឋាភិបាល', category: 'Culture & People' },
  { id: 128, english: 'Silk', khmer: 'សូត្រ', category: 'Culture & People' },
  { id: 129, english: 'Souvenir', khmer: 'វត្ថុអនុស្សាវរីយ៍', category: 'Culture & People' },
  { id: 130, english: 'Museum', khmer: 'សារមន្ទីរ', category: 'Culture & People' },

  // --- Food & Drink (60) ---
  { id: 131, english: 'Food', khmer: 'អាហារ', category: 'Food & Drink' },
  { id: 132, english: 'Water', khmer: 'ទឹក', category: 'Food & Drink' },
  { id: 133, english: 'Rice', khmer: 'បាយ', category: 'Food & Drink' },
  { id: 134, english: 'Noodle', khmer: 'គុយទាវ', category: 'Food & Drink' },
  { id: 135, english: 'Soup', khmer: 'ស៊ុប', category: 'Food & Drink' },
  { id: 136, english: 'Bread', khmer: 'នំបុ័ង', category: 'Food & Drink' },
  { id: 137, english: 'Meat', khmer: 'សាច់', category: 'Food & Drink' },
  { id: 138, english: 'Pork', khmer: 'សាច់ជ្រូក', category: 'Food & Drink' },
  { id: 139, english: 'Beef', khmer: 'សាច់គោ', category: 'Food & Drink' },
  { id: 140, english: 'Chicken', khmer: 'សាច់មាន់', category: 'Food & Drink' },
  { id: 141, english: 'Fish', khmer: 'ត្រី', category: 'Food & Drink' },
  { id: 142, english: 'Seafood', khmer: 'អាហារសមុទ្រ', category: 'Food & Drink' },
  { id: 143, english: 'Vegetable', khmer: 'បន្លែ', category: 'Food & Drink' },
  { id: 144, english: 'Fruit', khmer: 'ផ្លែឈើ', category: 'Food & Drink' },
  { id: 145, english: 'Mango', khmer: 'ស្វាយ', category: 'Food & Drink' },
  { id: 146, english: 'Banana', khmer: 'ចេក', category: 'Food & Drink' },
  { id: 147, english: 'Pineapple', khmer: 'ម្នាស់', category: 'Food & Drink' },
  { id: 148, english: 'Coconut', khmer: 'ដូង', category: 'Food & Drink' },
  { id: 149, english: 'Spicy', khmer: 'ហឹរ', category: 'Food & Drink' },
  { id: 150, english: 'Sweet', khmer: 'ផ្អែម', category: 'Food & Drink' },
  { id: 151, english: 'Sour', khmer: 'ជូរ', category: 'Food & Drink' },
  { id: 152, english: 'Salty', khmer: 'ប្រៃ', category: 'Food & Drink' },
  { id: 153, english: 'Delicious', khmer: 'ឆ្ងាញ់', category: 'Food & Drink' },
  { id: 154, english: 'Restaurant', khmer: 'ភោជនីយដ្ឋាន', category: 'Food & Drink' },
  { id: 155, english: 'Menu', khmer: 'ម៉ឺនុយ', category: 'Food & Drink' },
  { id: 156, english: 'Bill', khmer: 'វិក្កយបត្រ', category: 'Food & Drink' },
  { id: 157, english: 'Drink', khmer: 'ភេសជ្ជៈ', category: 'Food & Drink' },
  { id: 158, english: 'Coffee', khmer: 'កាហ្វេ', category: 'Food & Drink' },
  { id: 159, english: 'Tea', khmer: 'តែ', category: 'Food & Drink' },
  { id: 160, english: 'Beer', khmer: 'ស្រាបៀរ', category: 'Food & Drink' },
  { id: 161, english: 'Sugar', khmer: 'ស្ករ', category: 'Food & Drink' },
  { id: 162, english: 'Salt', khmer: 'អំបិល', category: 'Food & Drink' },
  { id: 163, english: 'Pepper', khmer: 'ម្រេច', category: 'Food & Drink' },
  { id: 164, english: 'Chili', khmer: 'ម្ទេស', category: 'Food & Drink' },
  { id: 165, english: 'Ice', khmer: 'ទឹកកក', category: 'Food & Drink' },
  { id: 166, english: 'Spoon', khmer: 'ស្លាបព្រា', category: 'Food & Drink' },
  { id: 167, english: 'Fork', khmer: 'សម', category: 'Food & Drink' },
  { id: 168, english: 'Knife', khmer: 'កាំបិត', category: 'Food & Drink' },
  { id: 169, english: 'Plate', khmer: 'ចាន', category: 'Food & Drink' },
  { id: 170, english: 'Bowl', khmer: 'ចានគោម', category: 'Food & Drink' },
  { id: 171, english: 'Glass', khmer: 'កែវ', category: 'Food & Drink' },
  { id: 172, english: 'Hungry', khmer: 'ឃ្លាន', category: 'Food & Drink' },
  { id: 173, english: 'Thirsty', khmer: 'ស្រេកទឹក', category: 'Food & Drink' },
  { id: 174, english: 'To eat', khmer: 'ញ៉ាំ', category: 'Food & Drink' },
  { id: 175, english: 'To drink', khmer: 'ផឹក', category: 'Food & Drink' },
  { id: 176, english: 'To cook', khmer: 'ចម្អិន', category: 'Food & Drink' },
  { id: 177, english: 'Amok', khmer: 'អាម៉ុក', category: 'Food & Drink' },
  { id: 178, english: 'Lok Lak', khmer: 'ឡុកឡាក់', category: 'Food & Drink' },
  { id: 179, english: 'Fried rice', khmer: 'បាយឆា', category: 'Food & Drink' },
  { id: 180, english: 'Spring roll', khmer: 'ចៃយ៉រ', category: 'Food & Drink' },
  { id: 181, english: 'Dessert', khmer: 'បង្អែម', category: 'Food & Drink' },
  { id: 182, english: 'Shrimp', khmer: 'បង្គា', category: 'Food & Drink' },
  { id: 183, english: 'Crab', khmer: 'ក្តាម', category: 'Food & Drink' },
  { id: 184, english: 'Egg', khmer: 'ពង', category: 'Food & Drink' },
  { id: 185, english: 'Garlic', khmer: 'ខ្ទឹមស', category: 'Food & Drink' },
  { id: 186, english: 'Onion', khmer: 'ខ្ទឹមបារាំង', category: 'Food & Drink' },
  { id: 187, english: 'Lemon', khmer: 'ក្រូចឆ្មា', category: 'Food & Drink' },
  { id: 188, english: 'Market stall', khmer: 'តូបលក់ដូរ', category: 'Food & Drink' },
  { id: 189, english: 'Street food', khmer: 'អាហារតាមផ្លូវ', category: 'Food & Drink' },
  { id: 190, english: 'Juice', khmer: 'ទឹកផ្លែឈើ', category: 'Food & Drink' },

  // --- Mountain Climbing (30) ---
  { id: 191, english: 'Mountain', khmer: 'ភ្នំ', category: 'Mountain Climbing' },
  { id: 192, english: 'Climb', khmer: 'ឡើង', category: 'Mountain Climbing' },
  { id: 193, english: 'Hike', khmer: 'ដើរភ្នំ', category: 'Mountain Climbing' },
  { id: 194, english: 'Peak', khmer: 'កំពូល', category: 'Mountain Climbing' },
  { id: 195, english: 'Summit', khmer: 'ចំណុចកំពូល', category: 'Mountain Climbing' },
  { id: 196, english: 'Trail', khmer: 'ផ្លូវលំ', category: 'Mountain Climbing' },
  { id: 197, english: 'Rock', khmer: 'ថ្ម', category: 'Mountain Climbing' },
  { id: 198, english: 'Rope', khmer: 'ខ្សែពួរ', category: 'Mountain Climbing' },
  { id: 199, english: 'Harness', khmer: 'ខ្សែរនាំង', category: 'Mountain Climbing' },
  { id: 200, english: 'Helmet', khmer: 'មួកសុវត្ថិភាព', category: 'Mountain Climbing' },
  { id: 201, english: 'Boots', khmer: 'ស្បែកជើងកវែង', category: 'Mountain Climbing' },
  { id: 202, english: 'Compass', khmer: 'ត្រីវិស័យ', category: 'Mountain Climbing' },
  { id: 203, english: 'Altitude', khmer: 'រយៈកម្ពស់', category: 'Mountain Climbing' },
  { id: 204, english: 'Viewpoint', khmer: 'ចំណុចមើលទេសភាព', category: 'Mountain Climbing' },
  { id: 205, english: 'Dangerous', khmer: 'គ្រោះថ្នាក់', category: 'Mountain Climbing' },
  { id: 206, english: 'Safe', khmer: 'សុវត្ថិភាព', category: 'Mountain Climbing' },
  { id: 207, english: 'Tired', khmer: 'ហត់', category: 'Mountain Climbing' },
  { id: 208, english: 'Rest', khmer: 'សម្រាក', category: 'Mountain Climbing' },
  { id: 209, english: 'Steep', khmer: 'ចោត', category: 'Mountain Climbing' },
  { id: 210, english: 'Path', khmer: 'ផ្លូវ', category: 'Mountain Climbing' },
  { id: 211, english: 'Guide', khmer: 'មគ្គុទ្ទេសក៍', category: 'Mountain Climbing' },
  { id: 212, english: 'Explore', khmer: 'រុករក', category: 'Mountain Climbing' },
  { id: 213, english: 'Cave', khmer: 'រូងភ្នំ', category: 'Mountain Climbing' },
  { id: 214, english: 'Cliff', khmer: 'ជ្រោះ', category: 'Mountain Climbing' },
  { id: 215, english: 'Scenery', khmer: 'ទេសភាព', category: 'Mountain Climbing' },
  { id: 216, english: 'Sunrise', khmer: 'ព្រះអាទិត្យរះ', category: 'Mountain Climbing' },
  { id: 217, english: 'Sunset', khmer: 'ព្រះអាទិត្យលិច', category: 'Mountain Climbing' },
  { id: 218, english: 'Campsite', khmer: 'កន្លែងបោះជំរុំ', category: 'Mountain Climbing' },
  { id: 219, english: 'Tent', khmer: 'តង់', category: 'Mountain Climbing' },
  { id: 220, english: 'Nature', khmer: 'ធម្មជាតិ', category: 'Mountain Climbing' },

  // --- Beach & Islands (30) ---
  { id: 221, english: 'Beach', khmer: 'ឆ្នេរ', category: 'Beach & Islands' },
  { id: 222, english: 'Sea', khmer: 'សមុទ្រ', category: 'Beach & Islands' },
  { id: 223, english: 'Ocean', khmer: 'មហាសមុទ្រ', category: 'Beach & Islands' },
  { id: 224, english: 'Island', khmer: 'កោះ', category: 'Beach & Islands' },
  { id: 225, english: 'Sand', khmer: 'ខ្សាច់', category: 'Beach & Islands' },
  { id: 226, english: 'Wave', khmer: 'រលក', category: 'Beach & Islands' },
  { id: 227, english: 'Sun', khmer: 'ព្រះអាទិត្យ', category: 'Beach & Islands' },
  { id: 228, english: 'Swim', khmer: 'ហែលទឹក', category: 'Beach & Islands' },
  { id: 230, english: 'Snorkeling', khmer: 'ការមុជទឹកមើលផ្កាថ្ម', category: 'Beach & Islands' },
  { id: 231, english: 'Diving', khmer: 'ការមុជទឹក', category: 'Beach & Islands' },
  { id: 232, english: 'Coral', khmer: 'ផ្កាថ្ម', category: 'Beach & Islands' },
  { id: 233, english: 'Shell', khmer: 'សំបកខ្យង', category: 'Beach & Islands' },
  { id: 234, english: 'Palm tree', khmer: 'ដើមត្នោត', category: 'Beach & Islands' },
  { id: 235, english: 'Relax', khmer: 'សម្រាក', category: 'Beach & Islands' },
  { id: 236, english: 'Sunscreen', khmer: 'ឡេការពារកម្តៅថ្ងៃ', category: 'Beach & Islands' },
  { id: 237, english: 'Sunglasses', khmer: 'វ៉ែនតាការពារកម្តៅថ្ងៃ', category: 'Beach & Islands' },
  { id: 238, english: 'Hat', khmer: 'មួក', category: 'Beach & Islands' },
  { id: 239, english: 'Fishing', khmer: 'នេសាទ', category: 'Beach & Islands' },
  { id: 240, english: 'Ferry', khmer: 'សាឡាង', category: 'Beach & Islands' },
  { id: 241, english: 'Coast', khmer: 'ឆ្នេរសមុទ្រ', category: 'Beach & Islands' },
  { id: 242, english: 'Pier', khmer: 'ផែ', category: 'Beach & Islands' },
  { id: 243, english: 'Resort', khmer: 'រមណីយដ្ឋាន', category: 'Beach & Islands' },
  { id: 244, english: 'Bungalow', khmer: 'បឹងហ្គាឡូ', category: 'Beach & Islands' },
  { id: 245, english: 'Tide', khmer: 'ជំនោរ', category: 'Beach & Islands' },
  { id: 246, english: 'Horizon', khmer: 'ជើងមេឃ', category: 'Beach & Islands' },
  { id: 247, english: 'Seagull', khmer: 'សត្វខ្លែងសមុទ្រ', category: 'Beach & Islands' },
  { id: 248, english: 'Hammock', khmer: 'អង្រឹង', category: 'Beach & Islands' },
  { id: 249, english: 'Fresh', khmer: 'ស្រស់', category: 'Beach & Islands' },
  { id: 250, english: 'Warm', khmer: 'ក្តៅ', category: 'Beach & Islands' },

  // --- Forest & Rivers (40) ---
  { id: 251, english: 'Forest', khmer: 'ព្រៃ', category: 'Forest & Rivers' },
  { id: 252, english: 'Jungle', khmer: 'ព្រៃ', category: 'Forest & Rivers' },
  { id: 253, english: 'Tree', khmer: 'ដើមឈើ', category: 'Forest & Rivers' },
  { id: 254, english: 'Leaf', khmer: 'ស្លឹកឈើ', category: 'Forest & Rivers' },
  { id: 255, english: 'Flower', khmer: 'ផ្កា', category: 'Forest & Rivers' },
  { id: 256, english: 'River', khmer: 'ទន្លេ', category: 'Forest & Rivers' },
  { id: 257, english: 'Lake', khmer: 'បឹង', category: 'Forest & Rivers' },
  { id: 258, english: 'Waterfall', khmer: 'ទឹកជ្រោះ', category: 'Forest & Rivers' },
  { id: 259, english: 'Animal', khmer: 'សត្វ', category: 'Forest & Rivers' },
  { id: 260, english: 'Bird', khmer: 'សត្វស្លាប', category: 'Forest & Rivers' },
  { id: 261, english: 'Insect', khmer: 'សត្វល្អិត', category: 'Forest & Rivers' },
  { id: 262, english: 'Mosquito', khmer: 'មូស', category: 'Forest & Rivers' },
  { id: 263, english: 'Snake', khmer: 'ពស់', category: 'Forest & Rivers' },
  { id: 264, english: 'Monkey', khmer: 'ស្វា', category: 'Forest & Rivers' },
  { id: 265, english: 'Elephant', khmer: 'ដំរី', category: 'Forest & Rivers' },
  { id: 266, english: 'Tiger', khmer: 'ខ្លា', category: 'Forest & Rivers' },
  { id: 267, english: 'Trekking', khmer: 'ការដើរព្រៃ', category: 'Forest & Rivers' },
  { id: 268, english: 'National Park', khmer: 'សួនជាតិ', category: 'Forest & Rivers' },
  { id: 269, english: 'Wood', khmer: 'ឈើ', category: 'Forest & Rivers' },
  { id: 270, english: 'Bamboo', khmer: 'ឫស្សី', category: 'Forest & Rivers' },
  { id: 271, english: 'Bridge', khmer: 'ស្ពាន', category: 'Forest & Rivers' },
  { id: 272, english: 'Stream', khmer: 'ស្ទឹង', category: 'Forest & Rivers' },
  { id: 273, english: 'Valley', khmer: 'ជ្រលងភ្នំ', category: 'Forest & Rivers' },
  { id: 274, english: 'Rain', khmer: 'ភ្លៀង', category: 'Forest & Rivers' },
  { id: 275, english: 'Weather', khmer: 'អាកាសធាតុ', category: 'Forest & Rivers' },
  { id: 276, english: 'Canopy', khmer: 'ដំបូលព្រៃ', category: 'Forest & Rivers' },
  { id: 277, english: 'Orchid', khmer: 'ផ្កាអ័រគីដេ', category: 'Forest & Rivers' },
  { id: 278, english: 'Wild', khmer: 'ព្រៃ', category: 'Forest & Rivers' },
  { id: 279, english: 'Ecosystem', khmer: 'ប្រព័ន្ធអេកូឡូស៊ី', category: 'Forest & Rivers' },
  { id: 280, english: 'Conservation', khmer: 'ការអភិរក្ស', category: 'Forest & Rivers' },
  { id: 281, english: 'Ranger', khmer: 'មន្ត្រីឧទ្យានុរក្ស', category: 'Forest & Rivers' },
  { id: 282, english: 'Biodiversity', khmer: 'ជីវចម្រុះ', category: 'Forest & Rivers' },
  { id: 283, english: 'Soil', khmer: 'ដី', category: 'Forest & Rivers' },
  { id: 284, english: 'Root', khmer: 'ឫស', category: 'Forest & Rivers' },
  { id: 285, english: 'Plant', khmer: 'រុក្ខជាតិ', category: 'Forest & Rivers' },
  { id: 286, english: 'Kayaking', khmer: 'ការចែវទូកកាយ៉ាក់', category: 'Forest & Rivers' },
  { id: 287, english: 'Firefly', khmer: 'អំពិលអំពែក', category: 'Forest & Rivers' },
  { id: 288, english: 'Butterfly', khmer: 'មេអំបៅ', category: 'Forest & Rivers' },
  { id: 289, english: 'Spider', khmer: 'សត្វពីងពាង', category: 'Forest & Rivers' },
  { id: 290, english: 'Bear', khmer: 'ខ្លាឃ្មុំ', category: 'Forest & Rivers' },

  // --- Animals (60) ---
  { id: 291, english: 'Dog', khmer: 'ឆ្កែ', category: 'Animals' },
  { id: 292, english: 'Cat', khmer: 'ឆ្មា', category: 'Animals' },
  { id: 293, english: 'Cow', khmer: 'គោ', category: 'Animals' },
  { id: 294, english: 'Buffalo', khmer: 'ក្របី', category: 'Animals' },
  { id: 295, english: 'Pig', khmer: 'ជ្រូក', category: 'Animals' },
  { id: 296, english: 'Duck', khmer: 'ទា', category: 'Animals' },
  { id: 297, english: 'Goat', khmer: 'ពពែ', category: 'Animals' },
  { id: 298, english: 'Horse', khmer: 'សេះ', category: 'Animals' },
  { id: 299, english: 'Rat', khmer: 'កណ្តុរ', category: 'Animals' },
  { id: 300, english: 'Frog', khmer: 'កង្កែប', category: 'Animals' },
  { id: 301, english: 'Gecko', khmer: 'តុកកែ', category: 'Animals' },
  { id: 302, english: 'Lizard', khmer: 'ជីងចក់', category: 'Animals' },
  { id: 303, english: 'Turtle', khmer: 'អណ្តើក', category: 'Animals' },
  { id: 304, english: 'Crocodile', khmer: 'ក្រពើ', category: 'Animals' },
  { id: 305, english: 'Dolphin', khmer: 'ផ្សោត', category: 'Animals' },
  { id: 306, english: 'Whale', khmer: 'ត្រីបាឡែន', category: 'Animals' },
  { id: 307, english: 'Shark', khmer: 'ត្រីឆ្លាម', category: 'Animals' },
  { id: 308, english: 'Jellyfish', khmer: 'ពពុះសមុទ្រ', category: 'Animals' },
  { id: 309, english: 'Eagle', khmer: 'ឥន្ទ្រី', category: 'Animals' },
  { id: 310, english: 'Owl', khmer: 'សត្វទីទុយ', category: 'Animals' },
  { id: 311, english: 'Bat', khmer: 'ប្រចៀវ', category: 'Animals' },
  { id: 312, english: 'Ant', khmer: 'ស្រមោច', category: 'Animals' },
  { id: 313, english: 'Bee', khmer: 'ឃ្មុំ', category: 'Animals' },
  { id: 314, english: 'Fly', khmer: 'រុយ', category: 'Animals' },
  { id: 315, english: 'Cockroach', khmer: 'កន្លាត', category: 'Animals' },
  { id: 316, english: 'Scorpion', khmer: 'ខ្យាដំរី', category: 'Animals' },
  { id: 317, english: 'Centipede', khmer: 'ក្អែប', category: 'Animals' },
  { id: 318, english: 'Gibbon', khmer: 'ស្វា', category: 'Animals' },
  { id: 319, english: 'Deer', khmer: 'សត្វក្តាន់', category: 'Animals' },
  { id: 320, english: 'Peacock', khmer: 'ក្ងោក', category: 'Animals' },
  { id: 321, english: 'Parrot', khmer: 'សេក', category: 'Animals' },
  { id: 322, english: 'Hornbill', khmer: 'កេងកង', category: 'Animals' },
  { id: 323, english: 'Pangolin', khmer: 'ពង្រូល', category: 'Animals' },
  { id: 324, english: 'Civet', khmer: 'សំពោច', category: 'Animals' },
  { id: 325, english: 'Mongoose', khmer: 'ចចុះ', category: 'Animals' },
  { id: 326, english: 'Otter', khmer: 'ភេ', category: 'Animals' },
  { id: 327, english: 'Leopard', khmer: 'ខ្លារខិន', category: 'Animals' },
  { id: 328, english: 'Wild Boar', khmer: 'ជ្រូកព្រៃ', category: 'Animals' },
  { id: 329, english: 'Sun Bear', khmer: 'ខ្លាឃ្មុំតូច', category: 'Animals' },
  { id: 330, english: 'Macaw', khmer: 'សេកម៉ាកាវ', category: 'Animals' },
  { id: 331, english: 'Cobra', khmer: 'ពស់វែក', category: 'Animals' },
  { id: 332, english: 'Python', khmer: 'ពស់ថ្លាន់', category: 'Animals' },
  { id: 333, english: 'Monitor Lizard', khmer: 'វារាន', category: 'Animals' },
  { id: 334, english: 'Termite', khmer: 'ដំបូក', category: 'Animals' },
  { id: 335, english: 'Grasshopper', khmer: 'កណ្ដូប', category: 'Animals' },
  { id: 336, english: 'Dragonfly', khmer: 'កន្ទុំរុយ', category: 'Animals' },
  { id: 337, english: 'Tarantula', khmer: 'អាពីង', category: 'Animals' },
  { id: 338, english: 'Stingray', khmer: 'បបែល', category: 'Animals' },
  { id: 339, english: 'Eel', khmer: 'អន្ទង់', category: 'Animals' },
  { id: 340, english: 'Snail', khmer: 'ខ្យង', category: 'Animals' },
  { id: 341, english: 'Clam', khmer: 'លៀស', category: 'Animals' },
  { id: 342, english: 'Mussel', khmer: 'គ្រំ', category: 'Animals' },
  { id: 343, english: 'Oyster', khmer: 'អយស្ទ័រ', category: 'Animals' },
  { id: 344, english: 'Squid', khmer: 'មឹក', category: 'Animals' },
  { id: 345, english: 'Octopus', khmer: 'រតី', category: 'Animals' },
  { id: 346, english: 'Starfish', khmer: 'ផ្កាយសមុទ្រ', category: 'Animals' },
  { id: 347, english: 'Sea urchin', khmer: 'អន្ទង់សមុទ្រ', category: 'Animals' },
  { id: 348, english: 'Sea cucumber', khmer: 'ត្រសក់សមុទ្រ', category: 'Animals' },
  { id: 349, english: 'Dugong', khmer: 'គោសមុទ្រ', category: 'Animals' },
  { id: 350, english: 'Banteng', khmer: 'ទន្សោង', category: 'Animals' },

  // --- Places of Interest (50) ---
  { id: 351, english: 'Angkor Wat', khmer: 'អង្គរវត្ត', category: 'Places of Interest' },
  { id: 352, english: 'Angkor Thom', khmer: 'អង្គរធំ', category: 'Places of Interest' },
  { id: 353, english: 'Bayon', khmer: 'ប្រាសាទបាយ័ន', category: 'Places of Interest' },
  { id: 354, english: 'Ta Prohm', khmer: 'ប្រាសាទតាព្រហ្ម', category: 'Places of Interest' },
  { id: 355, english: 'Banteay Srei', khmer: 'ប្រាសាទបន្ទាយស្រី', category: 'Places of Interest' },
  { id: 356, english: 'Phnom Penh', khmer: 'ភ្នំពេញ', category: 'Places of Interest' },
  { id: 357, english: 'Royal Palace', khmer: 'ព្រះបរមរាជវាំង', category: 'Places of Interest' },
  { id: 358, english: 'Silver Pagoda', khmer: 'វត្តព្រះកែវមរកត', category: 'Places of Interest' },
  { id: 359, english: 'Killing Fields', khmer: 'វាលពិឃាត', category: 'Places of Interest' },
  { id: 360, english: 'Tuol Sleng Museum', khmer: 'សារមន្ទីរទួលស្លែង', category: 'Places of Interest' },
  { id: 361, english: 'Siem Reap', khmer: 'សៀមរាប', category: 'Places of Interest' },
  { id: 362, english: 'Pub Street', khmer: 'ផ្លូវផាប់', category: 'Places of Interest' },
  { id: 363, english: 'Battambang', khmer: 'បាត់ដំបង', category: 'Places of Interest' },
  { id: 364, english: 'Bamboo Train', khmer: 'ណូរី', category: 'Places of Interest' },
  { id: 365, english: 'Kampot', khmer: 'កំពត', category: 'Places of Interest' },
  { id: 366, english: 'Bokor Mountain', khmer: 'ភ្នំបូកគោ', category: 'Places of Interest' },
  { id: 367, english: 'Kep', khmer: 'កែប', category: 'Places of Interest' },
  { id: 368, english: 'Crab Market', khmer: 'ផ្សារក្តាម', category: 'Places of Interest' },
  { id: 369, english: 'Sihanoukville', khmer: 'ព្រះសីហនុ', category: 'Places of Interest' },
  { id: 370, english: 'Koh Rong', khmer: 'កោះរ៉ុង', category: 'Places of Interest' },
  { id: 371, english: 'Koh Rong Samloem', khmer: 'កោះរ៉ុងសន្លឹម', category: 'Places of Interest' },
  { id: 372, english: 'Mondulkiri', khmer: 'មណ្ឌលគីរី', category: 'Places of Interest' },
  { id: 373, english: 'Ratanakiri', khmer: 'រតនគីរី', category: 'Places of Interest' },
  { id: 374, english: 'Tonlé Sap Lake', khmer: 'បឹងទន្លេសាប', category: 'Places of Interest' },
  { id: 375, english: 'Floating Village', khmer: 'ភូមិបណ្តែតទឹក', category: 'Places of Interest' },
  { id: 376, english: 'Preah Vihear', khmer: 'ប្រាសាទព្រះវិហារ', category: 'Places of Interest' },
  { id: 377, english: 'Koh Ker', khmer: 'កោះកេរ', category: 'Places of Interest' },
  { id: 378, english: 'Sambor Prei Kuk', khmer: 'សំបូរព្រៃគុហ៍', category: 'Places of Interest' },
  { id: 379, english: 'Oudong', khmer: 'ឧដុង្គ', category: 'Places of Interest' },
  { id: 380, english: 'Kampong Cham', khmer: 'កំពង់ចាម', category: 'Places of Interest' },
  { id: 381, english: 'Kratie', khmer: 'ក្រចេះ', category: 'Places of Interest' },
  { id: 382, english: 'Mekong River', khmer: 'ទន្លេមេគង្គ', category: 'Places of Interest' },
  { id: 383, english: 'Cardamom Mountains', khmer: 'ជួរភ្នំក្រវាញ', category: 'Places of Interest' },
  { id: 384, english: 'Central Market', khmer: 'ផ្សារធំថ្មី', category: 'Places of Interest' },
  { id: 385, english: 'Russian Market', khmer: 'ផ្សារទួលទំពូង', category: 'Places of Interest' },
  { id: 386, english: 'Wat Phnom', khmer: 'វត្តភ្នំ', category: 'Places of Interest' },
  { id: 387, english: 'Independence Monument', khmer: 'វិមានឯករាជ្យ', category: 'Places of Interest' },
  { id: 388, english: 'Pepper Farm', khmer: 'ចំការម្រេច', category: 'Places of Interest' },
  { id: 389, english: 'Salt Fields', khmer: 'វាលស្រែអំបិល', category: 'Places of Interest' },
  { id: 390, english: 'Rabbit Island', khmer: 'កោះទន្សាយ', category: 'Places of Interest' },
  { id: 391, english: 'Phnom Kulen', khmer: 'ភ្នំគូលែន', category: 'Places of Interest' },
  { id: 392, english: 'River of a Thousand Lingas', khmer: 'ក្បាលស្ពាន', category: 'Places of Interest' },
  { id: 393, english: 'Landmine Museum', khmer: 'សារមន្ទីរមីន', category: 'Places of Interest' },
  { id: 394, english: 'Silk Farm', khmer: 'កសិដ្ឋានសូត្រ', category: 'Places of Interest' },
  { id: 395, english: 'War Museum', khmer: 'សារមន្ទីរសង្គ្រាម', category: 'Places of Interest' },
  { id: 396, english: 'Artisans Angkor', khmer: 'សិប្បកម្មអង្គរ', category: 'Places of Interest' },
  { id: 398, english: 'Virachey National Park', khmer: 'ឧទ្យានជាតិវីរជ័យ', category: 'Places of Interest' },
  { id: 399, english: 'Yeak Laom Lake', khmer: 'បឹងយក្សឡោម', category: 'Places of Interest' },
  { id: 400, english: 'Wat Ek Phnom', khmer: 'វត្តឯកភ្នំ', category: 'Places of Interest' },
  
  // --- General & Common Words ---
  { id: 401, english: 'Yes', khmer: 'បាទ / ចាស', category: 'General' },
  { id: 402, english: 'No', khmer: 'ទេ', category: 'General' },
  { id: 403, english: 'Maybe', khmer: 'ប្រហែល', category: 'General' },
  { id: 404, english: 'Please', khmer: 'សូម', category: 'General' },
  { id: 424, english: 'Money', khmer: 'លុយ', category: 'General' },
  { id: 425, english: 'Change', khmer: 'លុយអាប់', category: 'General' },
  { id: 426, english: 'Expensive', khmer: 'ថ្លៃ', category: 'General' },
  { id: 427, english: 'Cheap', khmer: 'ថោក', category: 'General' },
  { id: 428, english: 'Discount', khmer: 'បញ្ចុះតម្លៃ', category: 'General' },
  { id: 429, english: 'ATM', khmer: 'អេធីអឹម', category: 'General' },
  { id: 430, english: 'Bank', khmer: 'ធនាគារ', category: 'General' },
  { id: 431, english: 'Hospital', khmer: 'មន្ទីរពេទ្យ', category: 'General' },
  { id: 432, english: 'Pharmacy', khmer: 'ឱសថស្ថាន', category: 'General' },
  { id: 433, english: 'Doctor', khmer: 'គ្រូពេទ្យ', category: 'General' },
  { id: 434, english: 'Police', khmer: 'ប៉ូលីស', category: 'General' },
  { id: 435, english: 'Emergency', khmer: 'គ្រាអាសន្ន', category: 'General' },
  { id: 437, english: 'Pain', khmer: 'ឈឺចាប់', category: 'General' },
  { id: 438, english: 'Fever', khmer: 'គ្រុន', category: 'General' },
  { id: 439, english: 'Medicine', khmer: 'ថ្នាំ', category: 'General' },
  { id: 440, english: 'Today', khmer: 'ថ្ងៃនេះ', category: 'General' },
  { id: 441, english: 'Yesterday', khmer: 'ម្សិលមិញ', category: 'General' },
  { id: 442, english: 'Tomorrow', khmer: 'ថ្ងៃស្អែក', category: 'General' },
  { id: 443, english: 'Now', khmer: 'ឥឡូវនេះ', category: 'General' },
  { id: 444, english: 'Later', khmer: 'ពេលក្រោយ', category: 'General' },
  { id: 445, english: 'Time', khmer: 'ម៉ោង', category: 'General' },
  { id: 447, english: 'Day', khmer: 'ថ្ងៃ', category: 'General' },
  { id: 448, english: 'Week', khmer: 'សប្តាហ៍', category: 'General' },
  { id: 449, english: 'Month', khmer: 'ខែ', category: 'General' },
  { id: 450, english: 'Year', khmer: 'ឆ្នាំ', category: 'General' },
  { id: 451, english: 'Monday', khmer: 'ថ្ងៃច័ន្ទ', category: 'General' },
  { id: 452, english: 'Tuesday', khmer: 'ថ្ងៃអង្គារ', category: 'General' },
  { id: 453, english: 'Wednesday', khmer: 'ថ្ងៃពុធ', category: 'General' },
  { id: 454, english: 'Thursday', khmer: 'ថ្ងៃព្រហស្បតិ៍', category: 'General' },
  { id: 455, english: 'Friday', khmer: 'ថ្ងៃសុក្រ', category: 'General' },
  { id: 456, english: 'Saturday', khmer: 'ថ្ងៃសៅរ៍', category: 'General' },
  { id: 457, english: 'Sunday', khmer: 'ថ្ងៃអាទិត្យ', category: 'General' },
  { id: 458, english: 'Zero', khmer: 'សូន្យ', category: 'General' },
  { id: 459, english: 'One', khmer: 'មួយ', category: 'General' },
  { id: 460, english: 'Two', khmer: 'ពីរ', category: 'General' },
  { id: 461, english: 'Three', khmer: 'បី', category: 'General' },
  { id: 462, english: 'Four', khmer: 'បួន', category: 'General' },
  { id: 463, english: 'Five', khmer: 'ប្រាំ', category: 'General' },
  { id: 464, english: 'Six', khmer: 'ប្រាំមួយ', category: 'General' },
  { id: 465, english: 'Seven', khmer: 'ប្រាំពីរ', category: 'General' },
  { id: 466, english: 'Eight', khmer: 'ប្រាំបី', category: 'General' },
  { id: 467, english: 'Nine', khmer: 'ប្រាំបួន', category: 'General' },
  { id: 468, english: 'Ten', khmer: 'ដប់', category: 'General' },
  { id: 469, english: 'Twenty', khmer: 'ម្ភៃ', category: 'General' },
  { id: 470, english: 'Fifty', khmer: 'ហាសិប', category: 'General' },
  { id: 471, english: 'One hundred', khmer: 'មួយរយ', category: 'General' },
  { id: 472, english: 'One thousand', khmer: 'មួយ​ពាន់', category: 'General' },
  { id: 473, english: 'Big', khmer: 'ធំ', category: 'General' },
  { id: 474, english: 'Small', khmer: 'តូច', category: 'General' },
  { id: 475, english: 'Hot', khmer: 'ក្តៅ', category: 'General' },
  { id: 476, english: 'Cold', khmer: 'ត្រជាក់', category: 'General' },
  { id: 477, english: 'Good', khmer: 'ល្អ', category: 'General' },
  { id: 478, english: 'Bad', khmer: 'អាក្រក់', category: 'General' },
  { id: 479, english: 'New', khmer: 'ថ្មី', category: 'General' },
  { id: 480, english: 'Old', khmer: 'ចាស់', category: 'General' },
  { id: 481, english: 'Open', khmer: 'បើក', category: 'General' },
  { id: 482, english: 'Closed', khmer: 'បិទ', category: 'General' },
  { id: 483, english: 'Internet', khmer: 'អ៊ីនធឺណិត', category: 'General' },
  { id: 484, english: 'Phone', khmer: 'ទូរស័ព្ទ', category: 'General' },
  { id: 485, english: 'Photo', khmer: 'រូបថត', category: 'General' },
  { id: 487, english: 'Why?', khmer: 'ហេតុអ្វី?', category: 'General' },
  { id: 488, english: 'When?', khmer: 'ពេលណា?', category: 'General' },
  { id: 489, english: 'Who?', khmer: 'អ្នកណា?', category: 'General' },
  { id: 490, english: 'Where?', khmer: 'ឯណា?', category: 'General' },
  { id: 491, english: 'How?', khmer: 'យ៉ាងម៉េច?', category: 'General' },
  { id: 492, english: 'Water pipe', khmer: 'ទុយោទឹក', category: 'General' },
  { id: 493, english: 'Chair', khmer: 'កៅអី', category: 'General' },
  { id: 494, english: 'Table', khmer: 'តុ', category: 'General' },
  { id: 495, english: 'House', khmer: 'ផ្ទះ', category: 'General' },
  { id: 496, english: 'School', khmer: 'សាលារៀន', category: 'General' },
  { id: 497, english: 'Work', khmer: 'ការងារ', category: 'General' },

  // --- Numbers (Continued) ---
  { id: 501, english: 'Eleven', khmer: 'ដប់មួយ', category: 'Numbers' },
  { id: 502, english: 'Twelve', khmer: 'ដប់ពីរ', category: 'Numbers' },
  { id: 503, english: 'Thirteen', khmer: 'ដប់បី', category: 'Numbers' },
  { id: 504, english: 'Fourteen', khmer: 'ដប់បួន', category: 'Numbers' },
  { id: 505, english: 'Fifteen', khmer: 'ដប់ប្រាំ', category: 'Numbers' },
  { id: 506, english: 'Sixteen', khmer: 'ដប់ប្រាំមួយ', category: 'Numbers' },
  { id: 507, english: 'Seventeen', khmer: 'ដប់ប្រាំពីរ', category: 'Numbers' },
  { id: 508, english: 'Eighteen', khmer: 'ដប់ប្រាំបី', category: 'Numbers' },
  { id: 509, english: 'Nineteen', khmer: 'ដប់ប្រាំបួន', category: 'Numbers' },
  { id: 510, english: 'Thirty', khmer: 'សាមសិប', category: 'Numbers' },
  { id: 511, english: 'Forty', khmer: 'សែសិប', category: 'Numbers' },
  { id: 512, english: 'Sixty', khmer: 'ហុកសិប', category: 'Numbers' },
  { id: 513, english: 'Seventy', khmer: 'ចិតសិប', category: 'Numbers' },
  { id: 514, english: 'Eighty', khmer: 'ប៉ែតសិប', category: 'Numbers' },
  { id: 515, english: 'Ninety', khmer: 'កៅសិប', category: 'Numbers' },
  { id: 516, english: 'Ten thousand', khmer: 'មួយម៉ឺន', category: 'Numbers' },

  // --- Cambodian Provinces & Cities ---
  { id: 520, english: 'Kampong Thom', khmer: 'កំពង់ធំ', category: 'Cambodian Places' },
  { id: 521, english: 'Kampong Speu', khmer: 'កំពង់ស្ពឺ', category: 'Cambodian Places' },
  { id: 522, english: 'Kampong Chhnang', khmer: 'កំពង់ឆ្នាំង', category: 'Cambodian Places' },
  { id: 523, english: 'Prey Veng', khmer: 'ព្រៃវែង', category: 'Cambodian Places' },
  { id: 524, english: 'Svay Rieng', khmer: 'ស្វាយរៀង', category: 'Cambodian Places' },
  { id: 525, english: 'Takeo', khmer: 'តាកែវ', category: 'Cambodian Places' },
  { id: 526, english: 'Pailin', khmer: 'ប៉ៃលិន', category: 'Cambodian Places' },
  { id: 527, english: 'Oddar Meanchey', khmer: 'ឧត្តរមានជ័យ', category: 'Cambodian Places' },
  { id: 528, english: 'Stung Treng', khmer: 'ស្ទឹងត្រែង', category: 'Cambodian Places' },
  { id: 529, english: 'Pursat', khmer: 'ពោធិ៍សាត់', category: 'Cambodian Places' },
  { id: 530, english: 'Koh Kong', khmer: 'កោះកុង', category: 'Cambodian Places' },
  { id: 531, english: 'Province', khmer: 'ខេត្ត', category: 'Cambodian Places' },
  
  // --- ASEAN Countries & Capitals ---
  { id: 540, english: 'Thailand', khmer: 'ប្រទេសថៃ', category: 'ASEAN' },
  { id: 541, english: 'Bangkok', khmer: 'បាងកក', category: 'ASEAN' },
  { id: 542, english: 'Laos', khmer: 'ប្រទេសឡាវ', category: 'ASEAN' },
  { id: 543, english: 'Vientiane', khmer: 'វៀងចន្ទន៍', category: 'ASEAN' },
  { id: 544, english: 'Vietnam', khmer: 'ប្រទេសវៀតណាម', category: 'ASEAN' },
  { id: 545, english: 'Hanoi', khmer: 'ហានូយ', category: 'ASEAN' },
  { id: 546, english: 'Malaysia', khmer: 'ប្រទេសម៉ាឡេស៊ី', category: 'ASEAN' },
  { id: 547, english: 'Kuala Lumpur', khmer: 'កូឡាឡាំពួរ', category: 'ASEAN' },
  { id: 548, english: 'Myanmar', khmer: 'ប្រទេសមីយ៉ាន់ម៉ា', category: 'ASEAN' },
  { id: 549, english: 'Naypyidaw', khmer: 'ណៃពិដោ', category: 'ASEAN' },
  { id: 550, english: 'Singapore', khmer: 'ប្រទេសសិង្ហបុរី', category: 'ASEAN' },
  { id: 551, english: 'Indonesia', khmer: 'ប្រទេសឥណ្ឌូនេស៊ី', category: 'ASEAN' },
  { id: 552, english: 'Jakarta', khmer: 'ចាការតា', category: 'ASEAN' },
  { id: 553, english: 'Philippines', khmer: 'ប្រទេសហ្វីលីពីន', category: 'ASEAN' },
  { id: 554, english: 'Manila', khmer: 'ម៉ានីល', category: 'ASEAN' },
  { id: 555, english: 'Brunei', khmer: 'ប្រទេសព្រុយណេ', category: 'ASEAN' },
  { id: 556, english: 'Bandar Seri Begawan', khmer: 'បង់ដាសេរីបេហ្គាវ៉ាន់', category: 'ASEAN' },
  { id: 557, english: 'Cambodia', khmer: 'ប្រទេសកម្ពុជា', category: 'ASEAN' },
  { id: 558, english: 'Capital City', khmer: 'រាជធានី', category: 'ASEAN' },
  { id: 559, english: 'Country', khmer: 'ប្រទេស', category: 'ASEAN' },
];

export const ALL_PHRASES: PhrasePair[] = [
  // Category: Greetings
  { id: 101, english: 'Hello', khmer: 'សួស្តី', category: 'Greetings' },
  { id: 102, english: 'How are you?', khmer: 'អ្នកសុខសប្បាយទេ?', category: 'Greetings' },
  { id: 103, english: 'I am fine, thank you.', khmer: 'ខ្ញុំសុខសប្បាយទេ អរគុណ។', category: 'Greetings' },
  { id: 104, english: 'What is your name?', khmer: 'តើអ្នកឈ្មោះអ្វី?', category: 'Greetings' },
  { id: 105, english: 'My name is...', khmer: 'ខ្ញុំឈ្មោះ...', category: 'Greetings' },
  { id: 106, english: 'Goodbye', khmer: 'លាហើយ', category: 'Greetings' },
  { id: 107, english: 'Thank you', khmer: 'អរគុណ', category: 'Greetings' },
  { id: 108, english: 'No problem', khmer: 'គ្មាន​បញ្ហា', category: 'Greetings' },
  { id: 109, english: 'Good luck', khmer: 'សូមសំណាងល្អ', category: 'Greetings' },
  
  // Category: Directions
  { id: 201, english: 'Where is the trail?', khmer: 'តើផ្លូវលំនៅឯណា?', category: 'Directions' },
  { id: 202, english: 'How far is it?', khmer: 'តើវាឆ្ងាយប៉ុណ្ណា?', category: 'Directions' },
  { id: 203, english: 'Is this the right way?', khmer: 'តើនេះជាផ្លូវត្រឹមត្រូវទេ?', category: 'Directions' },
  { id: 204, english: 'Turn left', khmer: 'បត់ឆ្វេង', category: 'Directions' },
  { id: 205, english: 'Turn right', khmer: 'បត់ស្តាំ', category: 'Directions' },
  { id: 206, english: 'Go straight', khmer: 'ទៅមុខត្រង់', category: 'Directions' },
  { id: 207, english: 'Where is the restroom?', khmer: 'តើបន្ទប់ទឹកនៅឯណា?', category: 'Directions' },

  // Category: Emergencies
  { id: 301, english: 'Help!', khmer: 'ជួយផង!', category: 'Emergencies' },
  { id: 302, english: 'I am lost.', khmer: 'ខ្ញុំវង្វេងផ្លូវ។', category: 'Emergencies' },
  { id: 303, english: 'I need a doctor.', khmer: 'ខ្ញុំត្រូវការគ្រូពេទ្យ។', category: 'Emergencies' },
  { id: 304, english: 'Is it dangerous?', khmer: 'តើវាគ្រោះថ្នាក់ទេ?', category: 'Emergencies' },
  { id: 305, english: 'I am sick', khmer: 'ខ្ញុំឈឺ', category: 'Emergencies' },

  // Category: Food & Drink
  { id: 401, english: 'I am hungry.', khmer: 'ខ្ញុំឃ្លាន។', category: 'Food & Drink' },
  { id: 402, english: 'I am thirsty.', khmer: 'ខ្ញុំស្រេកទឹក។', category: 'Food & Drink' },
  { id: 403, english: 'How much is this?', khmer: 'នេះតម្លៃប៉ុន្មាន?', category: 'Food & Drink' },
  { id: 404, english: 'The bill, please.', khmer: 'សូមគិតលុយ', category: 'Food & Drink' },
  { id: 405, english: 'I don\'t understand.', khmer: 'ខ្ញុំមិនយល់ទេ។', category: 'Food & Drink' },
  
];